# Generated by Django 5.1.6 on 2025-02-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('score', models.CharField(max_length=50)),
                ('text', models.TextField(unique=True)),
            ],
        ),
    ]
